version: '2'

services:
  mongo:
    image: mongo:3.6
    container_name: rmq_mongo
    volumes:
      - "db-data:/data/db"
    ports:
      - "27017:27017"
    command: --smallfiles

  rabbit:
     container_name: rmq_rabbit
     hostname: rabbit
     image: rabbitmq:3.7-management
     environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
     ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
    container_name: zssn-api
    command: npm run dev
    volumes:
      - .:/usr/src/api
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - mongo
      - rabbit
    environment:
      - PORT=8080
      - NODE_ENV=development
      - MONGODB_URI="mongodb://mongo:27017/rmq"

volumes:
  db-data:
